# Generated by Django 4.2.3 on 2023-09-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_reservaservicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaservicio',
            old_name='Servicio',
            new_name='servicio',
        ),
    ]
